import { Fraunces } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ['300', '400', '200', '600', '700', '800', '900'],
  variable: "--font-fraunces",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fraunces.className}>
        <Header />
        {children}</body>
    </html>
  );
}
